# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-11 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_num', models.IntegerField(max_length=10)),
                ('company', models.CharField(max_length=100)),
                ('cust_rep', models.IntegerField(max_length=10)),
                ('credit_limit', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('mgr', models.IntegerField(max_length=10)),
                ('target_sales', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfr_id', models.IntegerField(max_length=10)),
                ('product_id', models.IntegerField(max_length=10)),
                ('order_date', models.DateTimeField(verbose_name='order date')),
                ('order_num', models.IntegerField(max_length=10)),
                ('qty', models.IntegerField(max_length=10)),
                ('amount', models.IntegerField(max_length=10)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfr_id', models.IntegerField(max_length=10)),
                ('product_id', models.IntegerField(max_length=10)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField(max_length=10)),
                ('qty_in_hand', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Salesrep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_num', models.IntegerField(max_length=10)),
                ('mgr', models.IntegerField(max_length=10)),
                ('hire_date', models.DateTimeField(verbose_name='hire date')),
                ('age', models.IntegerField(max_length=10)),
                ('quota', models.IntegerField(max_length=10)),
                ('sales', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('rep_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.Office')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='sales_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.Salesrep'),
        ),
    ]
