# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-11 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_num',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_rep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='office',
            name='mgr',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='office',
            name='office',
            field=models.IntegerField(unique='True'),
        ),
        migrations.AlterField(
            model_name='office',
            name='target_sales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='mfr_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='mfr_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty_in_hand',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='emp_num',
            field=models.IntegerField(unique='True'),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='mgr',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='quota',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='sales',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
        migrations.AlterModelTable(
            name='office',
            table='Office',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='salesrep',
            table='Salesrep',
        ),
    ]
